server:
    port: 8080

spring:
  application:
    name: ronin-airbnb

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/airbnb
    username: user
    password: pass
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

payment:
  vnpay:
    tmn-code: RONINHUB
    secret-key: ${VNPAY_SECRET_KEY}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://dev.roninhub.com/order/%s/status
    timeout: 15 # in minutes

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
